server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ssar
    password: ssar1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create(실행시 테이블을 새로만든다), update는 데이터를 변경한다. none 일경우 기존에 데이터가 있는 테이블의 경우 none 을 사용한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false # jpa 의 넘버링 전략을 따라가지 않겠다.
    show-sql: true
    properties:
      hibernate.format_sql: true # 콘솔에 테이블 생성 및 업데이트시 정렬된 결과로 보여준다.

  jackson:
    serialization:
      fail-on-empty-beans: false